### ISSUE TITLE
你好，使用安卓appkey集成后查看不到基础统计数据，埋点事件也没生效

### ISSUE THREAD

**Issue by 370966584** [MrLiuYS/lcfarm_flutter_umeng#1]
![image](https://user-images.githubusercontent.com/26058251/57444809-935ae280-7283-11e9-83a6-da8d351cedbb.png)
![image](https://user-images.githubusercontent.com/26058251/57444846-aa013980-7283-11e9-9bb2-03f5fdc844c8.png)

**Comment by MrLiuYS** [comment]
example.没有数据.但是基层到项目中.是有数据的.你可以试试集成到项目中看看

**Comment by jendy2012** [comment]
使用安卓的AppKey集成后查看不到基础统计数据，埋点事件也没生效
确实没有。
集成进去也没有效果。

**Comment by MrLiuYS** [comment]
> 使用安卓的AppKey集成后查看不到基础统计数据，埋点事件也没生效
> 确实没有。
> 集成进去也没有效果。

android项目需要在MainActivity.java添加方法

  public void onResume() {
    super.onResume();
    MobclickAgent.onResume(this);

  }

  public void onPause() {
    super.onPause();
    MobclickAgent.onPause(this);
  }
当然记得引入

import com.umeng.analytics.MobclickAgent;

**Comment by marvin-min** [comment]
我也遇到这样的问题了。解决了没。楼主

**Comment by MrLiuYS** [comment]
android项目需要在MainActivity.java添加方法

  public void onResume() {
    super.onResume();
    MobclickAgent.onResume(this);

  }

  public void onPause() {
    super.onPause();
    MobclickAgent.onPause(this);
  }


Marvin.Min <notifications@github.com> 于2019年10月29日周二 下午1:07写道：

**Comment by MrLiuYS** [comment]
> 我也遇到这样的问题了。解决了没。楼主

回答了啊。这么处理之后。可能页面的跳转统计会有点问题。但是问题不大

**Comment by marvin-min** [comment]
没有页面跳转
你说的代码也加了：
https://github.com/marvin-min/flutter_demo/blob/master/android/app/src/main/java/com/yzgw365/flutter_demo/MainActivity.java

**Comment by marvin-min** [comment]
@370966584 你这个问题解决了么？可否帮我看一下？
