### ISSUE TITLE
关于页面的统计

### ISSUE THREAD

**Issue by lgj860123** [MrLiuYS/lcfarm_flutter_umeng#11]
你好，使用了你这个插件，但是好像不能统计，你自己写这个插件的时候，有做过测试没有呢？像遇到这个问题如何解决呢？希望大佬帮忙修复下这个插件的问题，谢谢！

**Comment by MrLiuYS** [comment]
额。必须有验证啊。要不然你运行example。里面的key换成你自己的，就知道有没有问题了。Android的记得看下readme
