### ISSUE TITLE
swift项目用不了啊

### ISSUE THREAD

**Issue by lbx-ai** [MrLiuYS/lcfarm_flutter_umeng#2]

**Comment by lbx-ai** [comment]
怎么解决啊

**Comment by lbx-ai** [comment]
是需要添加这个 s.static_framework = true 到podspec文件
但是现在卡在初始化了

**Comment by MrLiuYS** [comment]
flutter项目。对OC跟Swift混编不是很友好.目前这个项目是OC的项目。等我有时间我将swift也补上吧。

**Comment by MrLiuYS** [comment]
> 是需要添加这个s.static_framework = true到podspec文件
> 但是现在卡在初始化了

**Comment by MrLiuYS** [comment]
dependencies:
  lcfarm_flutter_umeng: ^0.1.5
