### ISSUE TITLE
怎么设置渠道

### ISSUE THREAD

**Issue by 0-php** [MrLiuYS/lcfarm_flutter_umeng#3]
怎么设置渠道

**Comment by MrLiuYS** [comment]
> 怎么设置渠道

static Future<bool> init({
    String iOSAppKey,
    String androidAppKey,
    String channel, //渠道标识

    bool logEnable, //设置是否在console输出sdk的log信息.

    bool encrypt, //设置是否对日志信息进行加密, 默认NO(不加密).设置为YES, umeng SDK 会将日志信息做加密处理
  })
