### ISSUE TITLE
哭了，新手不会玩，能不能远程带带我

### ISSUE THREAD

**Issue by forever-z-133** [MrLiuYS/lcfarm_flutter_umeng#8]
感觉要配的都配上了，console 也打印了 SDK 初始化成功，
但友盟后台上 U-App验证失败，也不会有数据变化。

大佬能不能扣扣连个远程带我玩下，感激不尽，QQ: 617754841

**Comment by MrLiuYS** [comment]
你直接用example .    LcfarmFlutterUmeng.init(
      iOSAppKey: "xxxxx",
      androidAppKey: "xxxx",
      channel: "test1",
      logEnable: true
    );
试试看可不可以?
