### ISSUE TITLE
ios无法编译

### ISSUE THREAD

**Issue by deboLing** [MrLiuYS/lcfarm_flutter_umeng#9]
iOS运行报错，执行pod install后，出现如下异常：
[!] CDN: trunk Repo update failed - 15 error(s):
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/0.1-beta/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.4.1/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.4.1beta/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.4.1internation/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.4.2/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.4.3/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.5.0/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.5.1/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.5.2/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/1.5.3/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/2.0.0/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/2.0.1/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/2.1.0/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/2.1.1/UMCCommon.podspec.json Response: Couldn't connect to server
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/b/6/UMCCommon/2.1.4/UMCCommon.podspec.json Response: Couldn't connect to server

连不上友盟相关的服务啥的

怎么处理呢

**Comment by MrLiuYS** [comment]
这个应该是cocoapods,加载库的问题.可以试试翻墙.然后再pod install
